spring:
  application:
    name: ClimbingApp
  datasource:
    url: jdbc:mysql://localhost:3306/climbing_app?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: n3486T74
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # can also be "create", "validate", or "none"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
